"""Tests for ``fs.read`` (``shell/fs/read.py``).

Three properties matter more than the rest of this file:

* **numbering precedes truncation** -- pinned two ways: byte-for-byte against
  colleague's own captured fixture (the strongest proof available, since that
  fixture was generated by colleague's real ``_read_file`` at the pinned SHA),
  and against a local "wrong order" reference reimplementation that a
  reversed refactor here would start matching instead;
* **a handler crash on malformed input is a recoverable ``FAILED`` result,
  never a raised exception** -- exercised with the exact NUL-byte case
  colleague's own characterization capture used to prove the same thing
  (``scripts/capture_colleague_baseline.py``, ``execute_wraps_non_tool_error``);
* **confinement covers a symlink escape, not just a literal ``../``** -- a
  symlink placed *inside* the work root that points *outside* it must be
  refused exactly like a literal escape, because ``Path.resolve()`` follows
  the symlink before the containment check ever runs.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Callable

import pytest

from shell import operations
from shell.environment import DEFAULT_MAX_OUTPUT_BYTES, Environment, WorkspaceKind
from shell.evidence import EvidenceRecord
from shell.fs import read as fs_read
from shell.operations import ExecutionProfile, Operation, OperationIntent
from shell.results import SCHEMA_VERSION, OperationResult, OperationStatus
from shell.runners.host import HostRunner

_FIXTURE_PATH = Path(__file__).parent / "fixtures" / "colleague" / "behavior.json"


def _load_fixture(name: str) -> dict:
    payload = json.loads(_FIXTURE_PATH.read_text(encoding="utf-8"))
    return payload["behaviors"][name]


@pytest.fixture
def env(tmp_path: Path) -> Environment:
    source = tmp_path / "source"
    work = tmp_path / "work"
    source.mkdir()
    work.mkdir()
    return Environment(
        source_root=source,
        work_root=work,
        runner=HostRunner(),
        workspace=WorkspaceKind.WORKTREE,
    )


def _read(env: Environment, arguments: dict, **kwargs) -> OperationResult:
    operation = Operation(kind=fs_read.KIND, arguments=arguments, **kwargs)
    return operations.execute(operation, env)


def _sink() -> tuple[list[EvidenceRecord], Callable[[EvidenceRecord], None]]:
    records: list[EvidenceRecord] = []
    return records, records.append


# --- registration -------------------------------------------------------


def test_fs_read_self_registers_on_import() -> None:
    assert fs_read.KIND in operations.registered_kinds()


def test_fs_read_is_an_observe_intent_operation() -> None:
    normalized = operations.normalize(Operation(kind=fs_read.KIND, arguments={"path": "x"}))
    assert normalized.intent is OperationIntent.OBSERVE
    assert normalized.profile is ExecutionProfile.OBSERVE
    # Observations never require --apply/apply=True; a read executes immediately.
    assert normalized.requires_apply is False


# --- basic numbering shape ------------------------------------------------


def test_read_numbers_lines_cat_n_style(env: Environment) -> None:
    (env.work_root / "a.txt").write_text("alpha\nbeta\n", encoding="utf-8")
    result = _read(env, {"path": "a.txt"})

    assert result.succeeded
    assert result.rendering == "     1\talpha\n     2\tbeta"
    assert result.output["path"] == "a.txt"
    assert result.output["truncated"] is False
    assert result.effects.complete is True
    assert result.effects.changed_paths == ()
    assert result.schema_version == SCHEMA_VERSION


def test_read_of_an_empty_file_grounds_to_an_empty_string(env: Environment) -> None:
    (env.work_root / "empty.txt").write_text("", encoding="utf-8")
    result = _read(env, {"path": "empty.txt"})

    assert result.succeeded
    assert result.rendering == ""


def test_read_does_not_mint_a_phantom_line_for_a_trailing_newline(env: Environment) -> None:
    (env.work_root / "trail.txt").write_text("one\ntwo\n", encoding="utf-8")
    result = _read(env, {"path": "trail.txt"})

    assert result.rendering.count("\t") == 2
    assert result.rendering.splitlines()[-1].endswith("two")


# --- the load-bearing ordering property: number THEN truncate -------------


def test_read_matches_colleagues_captured_fixture_byte_for_byte(env: Environment) -> None:
    """The strongest available proof: replay colleague's own captured input
    against this handler and require the rendering to be byte-identical to
    what colleague's real ``_read_file`` produced at the pinned SHA
    (28fee290c51fc4310b9fc576981809ad5c3132c6). If this handler ever
    truncated before numbering, this assertion fails -- the fixture's
    ``result`` was generated with the correct order and nothing else."""
    fixture = _load_fixture("read_file_numbers_then_truncates")
    assert fixture["max_output_chars"] == DEFAULT_MAX_OUTPUT_BYTES

    (env.work_root / "big.txt").write_text(fixture["input_text"], encoding="utf-8")
    result = _read(env, {"path": "big.txt"})

    assert result.succeeded
    assert result.rendering == fixture["result"]
    assert result.output["truncated"] is True


def _number_lines_reference(text: str, width: int) -> str:
    """A standalone reimplementation of the CORRECT numbering step, used only
    to build the WRONG (truncate-first) order below for comparison -- it never
    substitutes for the real handler's own numbering."""
    if text == "":
        return ""
    body = text[:-1] if text.endswith("\n") else text
    lines = body.split("\n")
    return "\n".join(f"{i:{width}d}\t{line}" for i, line in enumerate(lines, start=1))


def _truncate_reference(text: str, limit: int) -> str:
    if len(text) <= limit:
        return text
    return text[:limit] + f"\n... [truncated at {limit} chars]"


def test_read_would_differ_if_numbering_and_truncation_were_reversed(env: Environment) -> None:
    """Constructs the WRONG order (truncate raw text, then number what
    survives) locally and asserts the real handler's output does NOT match
    it. A refactor that reversed the two steps inside ``shell/fs/read.py``
    would make this assertion fail, because the handler's rendering would
    start equalling ``wrong_order`` instead of diverging from it."""
    lines = [f"line{i:05d}_payload_padding_{'x' * 25}" for i in range(1, 1001)]
    raw = "\n".join(lines) + "\n"
    (env.work_root / "big.txt").write_text(raw, encoding="utf-8")

    result = _read(env, {"path": "big.txt"})

    wrong_order = _number_lines_reference(_truncate_reference(raw, DEFAULT_MAX_OUTPUT_BYTES), 6)

    assert result.rendering != wrong_order
    # Concretely: numbering-after-truncation gives the truncation marker
    # itself a phantom line number, because it now runs over text that
    # already contains "... [truncated at N chars]" as if it were real file
    # content. The correct (number-first) order never does this.
    assert "\t... [truncated at" in wrong_order
    assert "\t... [truncated at" not in result.rendering


def test_read_last_visible_line_carries_its_true_file_line_number(env: Environment) -> None:
    """A cited line number must be copy-derived from the real file, never
    re-counted from a truncated/windowed remainder (colleague issue #240)."""
    lines = [f"line{i:05d}_payload_padding_{'x' * 25}" for i in range(1, 1001)]
    raw = "\n".join(lines) + "\n"
    (env.work_root / "big.txt").write_text(raw, encoding="utf-8")

    result = _read(env, {"path": "big.txt"})
    assert result.output["truncated"] is True

    body = result.rendering.split("\n... [truncated", 1)[0]
    last_line = body.rstrip("\n").split("\n")[-1]
    number_str, _, content = last_line.partition("\t")
    # "   424\tline00424_..." -- the numeric prefix must match the numeric
    # suffix embedded in the line's own content, proving it is the TRUE file
    # line, not a position renumbered within the truncated chunk.
    assert content.startswith(f"line{int(number_str):05d}_")


# --- recoverable, model-visible errors -------------------------------------


def test_missing_required_path_is_a_recoverable_failed_result(env: Environment) -> None:
    result = _read(env, {})

    assert result.status is OperationStatus.FAILED
    assert "path" in result.error


def test_no_such_file_is_a_recoverable_failed_result(env: Environment) -> None:
    result = _read(env, {"path": "does/not/exist.txt"})

    assert result.status is OperationStatus.FAILED
    assert "no such file" in result.error


def test_reading_a_directory_is_a_recoverable_failed_result(env: Environment) -> None:
    (env.work_root / "adir").mkdir()
    result = _read(env, {"path": "adir"})

    assert result.status is OperationStatus.FAILED
    assert "cannot read" in result.error


def test_dot_dot_path_escape_is_refused(env: Environment) -> None:
    outside = env.work_root.parent / "secret.txt"
    outside.write_text("do not read me", encoding="utf-8")

    result = _read(env, {"path": "../secret.txt"})

    assert result.status is OperationStatus.FAILED
    assert "escapes the work root" in result.error


def test_absolute_path_escape_is_refused(env: Environment) -> None:
    outside = env.work_root.parent / "secret2.txt"
    outside.write_text("do not read me either", encoding="utf-8")

    result = _read(env, {"path": str(outside)})

    assert result.status is OperationStatus.FAILED
    assert "escapes the work root" in result.error


def test_symlink_inside_root_pointing_outside_it_is_refused(env: Environment) -> None:
    """The interesting confinement case: the literal path string
    (``link.txt``) never mentions anything outside the root, but resolving
    the symlink lands outside it. A confinement check that only inspects the
    literal path string -- rather than the resolved target -- would miss
    this and let the read through."""
    outside_dir = env.work_root.parent / "outside"
    outside_dir.mkdir()
    secret = outside_dir / "secret.txt"
    secret.write_text("outside content", encoding="utf-8")

    link = env.work_root / "link.txt"
    os.symlink(secret, link)

    result = _read(env, {"path": "link.txt"})

    assert result.status is OperationStatus.FAILED
    assert "escapes the work root" in result.error


def test_symlinked_directory_inside_root_pointing_outside_it_is_refused(
    env: Environment,
) -> None:
    """The same escape, one level up: a symlinked *directory* inside the
    root whose target lives outside it, reached through a nested relative
    path (``linked_dir/secret.txt``)."""
    outside_dir = env.work_root.parent / "outside_dir"
    outside_dir.mkdir()
    (outside_dir / "secret.txt").write_text("outside content", encoding="utf-8")

    link_dir = env.work_root / "linked_dir"
    os.symlink(outside_dir, link_dir, target_is_directory=True)

    result = _read(env, {"path": "linked_dir/secret.txt"})

    assert result.status is OperationStatus.FAILED
    assert "escapes the work root" in result.error


def test_a_normal_symlink_that_stays_inside_the_root_is_readable(env: Environment) -> None:
    """The confinement check must not be so aggressive it refuses a symlink
    that resolves to a target still inside the work root."""
    real = env.work_root / "real.txt"
    real.write_text("hello\n", encoding="utf-8")
    link = env.work_root / "alias.txt"
    os.symlink(real, link)

    result = _read(env, {"path": "alias.txt"})

    assert result.succeeded
    assert result.rendering == "     1\thello"


# --- a handler crash on malformed input: recoverable, never a run abort ---


def test_a_nul_byte_in_the_path_crashes_the_handler_but_is_recovered() -> None:
    """Reproduces colleague's own characterization case
    (``scripts/capture_colleague_baseline.py``, ``execute_wraps_non_tool_error``):
    a NUL byte in the path makes ``Path.resolve()`` raise a bare
    ``ValueError`` deep inside ``_safe_path``. This module deliberately does
    not catch it -- proving that ``operations.execute``'s handler-crash wrap
    (not this module) is what turns it into a recoverable ``FAILED`` result,
    never lets it escape as a raised exception, and records the crash
    honestly rather than as an ordinary policy-driven failure."""
    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        source = Path(tmp) / "source"
        work = Path(tmp) / "work"
        source.mkdir()
        work.mkdir()
        env = Environment(
            source_root=source,
            work_root=work,
            runner=HostRunner(),
            workspace=WorkspaceKind.WORKTREE,
        )

        records, sink = _sink()
        operation = Operation(kind=fs_read.KIND, arguments={"path": "a\x00b"})

        # The point of the test: this call must not raise.
        result = operations.execute(operation, env, evidence_sink=sink)

    assert result.status is OperationStatus.FAILED
    assert "ValueError" in result.error
    assert fs_read.KIND in result.error

    execution = records[0].to_dict()["execution"]
    assert execution["handler_entered"] is True
    assert execution["handler_disposition"] == "crashed"
    # A crashed handler's "did it apply anything?" is unknowable, not false.
    assert execution["applied"] is None


def test_the_raw_handler_call_is_not_wrapped_without_execute(env: Environment) -> None:
    """Without ``operations.execute``'s wrap, the identical crash escapes as
    a raw, unrecoverable exception -- proof the wrap does real work rather
    than relabelling something that was already safe."""
    operation = Operation(kind=fs_read.KIND, arguments={"path": "a\x00b"})

    with pytest.raises(ValueError):
        fs_read._read(operation, env)


# --- fs.* is not gated by the run_command policy ---------------------------


def test_fs_read_is_ungated_regardless_of_policy(env: Environment) -> None:
    """``fs.*`` is deliberately outside the run_command policy's
    jurisdiction (pinned upstream by
    tests/test_loop_run_command_policy.py:366-386 in colleague) -- confirmed
    here rather than assumed, since a caller could otherwise believe a
    denied policy blocks reads too."""
    from shell.policy import Policy

    (env.work_root / "gated.txt").write_text("content\n", encoding="utf-8")
    # A run_command section present and denying everything -- proves fs.read
    # succeeds even under a policy that would deny any gated operation, since
    # fs.* is outside check_run_command's jurisdiction entirely.
    deny_everything = Policy(
        run_command={"deny": ["anything"]},
        present=frozenset({"run_command"}),
    )

    operation = Operation(kind=fs_read.KIND, arguments={"path": "gated.txt"})
    result = operations.execute(operation, env, policy=deny_everything)

    assert result.status is OperationStatus.SUCCEEDED
    assert result.verdict.decision.value == "ungated"


# --- resource limit override -----------------------------------------------


def test_max_output_bytes_override_shrinks_the_truncation_window(env: Environment) -> None:
    (env.work_root / "small.txt").write_text("a\nb\nc\nd\n", encoding="utf-8")

    result = _read(env, {"path": "small.txt"}, max_output_bytes=5)

    assert result.output["truncated"] is True
    assert "truncated at 5 chars" in result.rendering
