"""Assertions over the captured colleague handler behaviour (t74a AC5).

Every value asserted here was generated by
``scripts/capture_colleague_baseline.py`` against a live colleague checkout
(``tests/fixtures/colleague/behavior.json``) -- these tests read that
committed fixture, they never need a colleague checkout themselves, so they
run unconditionally (including in CI, which has none).
"""

from __future__ import annotations

from tests.characterization.fixtures import load_behavior

_BEHAVIOR = load_behavior()
_CONSTANTS = _BEHAVIOR["constants"]
_B = _BEHAVIOR["behaviors"]


# --- constants ---------------------------------------------------------


def test_max_output_chars_inlines_as_25000():
    assert _CONSTANTS["max_output_chars"] == 25000


def test_max_media_bytes_is_4_mebibytes():
    assert _CONSTANTS["max_media_bytes"] == 4 * 1024 * 1024


def test_line_number_width_is_6_cat_dash_n_style():
    assert _CONSTANTS["line_number_width"] == 6


# --- read_file: numbering happens BEFORE truncation (issue #240) -------
#
# A local reimplementation of colleague's own documented contract
# (colleague/tools.py:599-621, _number_lines) is used ONLY to construct the
# WRONG order for comparison below -- it never substitutes for colleague's
# own numbering, which the captured fixture already pins byte-for-byte.


def _number_lines_reference(text: str, width: int) -> str:
    if text == "":
        return ""
    body = text[:-1] if text.endswith("\n") else text
    lines = body.split("\n")
    return "\n".join(f"{i:{width}d}\t{line}" for i, line in enumerate(lines, start=1))


def _truncate_reference(text: str, limit: int) -> str:
    if len(text) <= limit:
        return text
    return text[:limit] + f"\n... [truncated at {limit} chars]"


def test_read_file_result_is_truncated():
    fixture = _B["read_file_numbers_then_truncates"]
    assert fixture["ok"] is True
    assert len(fixture["input_text"]) > _CONSTANTS["max_output_chars"]
    assert "truncated at" in fixture["result"]


def test_read_file_would_differ_if_numbering_and_truncation_were_reversed():
    """The load-bearing ordering fixture: reimplementing the WRONG order
    (truncate raw text first, number what survives second) must NOT
    reproduce what colleague actually captured. If a future refactor
    reversed the two steps, this test is the one that catches it."""
    fixture = _B["read_file_numbers_then_truncates"]
    raw = fixture["input_text"]
    correct = fixture["result"]

    wrong_order = _number_lines_reference(
        _truncate_reference(raw, fixture["max_output_chars"]),
        fixture["line_number_width"],
    )

    assert wrong_order != correct
    # Concretely: numbering-after-truncation gives the truncation marker
    # itself a phantom line number, because it now runs over text that
    # already contains "... [truncated at N chars]" as if it were real
    # file content. The correct (number-first) order never does this --
    # the marker is appended AFTER numbering completes.
    assert "\t... [truncated at" in wrong_order
    assert "\t... [truncated at" not in correct


def test_read_file_last_visible_line_carries_its_true_file_line_number():
    """A cited line number must be copy-derived from the real file, never
    re-counted from a truncated/windowed remainder (colleague issue #240)."""
    fixture = _B["read_file_numbers_then_truncates"]
    result = fixture["result"]
    body = result.split("\n... [truncated", 1)[0]
    last_line = body.rstrip("\n").split("\n")[-1]
    # "   424\tline00424_..." -- the numeric prefix must match the numeric
    # suffix of the line's own content, proving it is the TRUE file line,
    # not a renumbered position within the truncated chunk.
    number_str, _, content = last_line.partition("\t")
    assert content.startswith(f"line{int(number_str):05d}_")


def test_read_file_missing_required_path_is_a_recoverable_tool_error():
    fixture = _B["read_file_missing_required_path"]
    assert fixture["ok"] is False
    assert fixture["error_type"] == "ToolError"
    assert "path" in fixture["error"]


def test_read_file_path_escape_is_refused():
    fixture = _B["read_file_path_escape"]
    assert fixture["ok"] is False
    assert "escapes the repo root" in fixture["error"]


# --- write_file / edit_file: bytes_written accounting -------------------


def test_write_file_bytes_written_is_the_full_content():
    fixture = _B["write_file_bytes_written"]
    assert fixture["ok"] is True
    assert fixture["bytes_written"] == len("hello world".encode("utf-8")) == 11
    assert fixture["result"] == "wrote 11 bytes to w.txt"
    assert fixture["changed"] == ["w.txt"]


def test_write_file_creates_missing_parent_directories():
    fixture = _B["write_file_creates_nested_dirs"]
    assert fixture["ok"] is True
    assert fixture["changed_file"] == "nested/deep/file.txt"


def test_edit_file_bytes_written_is_replacement_only_not_the_whole_file():
    """'AAAA BBBB CCCC' (14 bytes) has 'BBBB' replaced with 'XY' (2 bytes) --
    bytes_written must count only the 2 replacement bytes, the honest
    cost-of-output signal, not the 14-byte file."""
    fixture = _B["edit_file_bytes_written_single"]
    assert fixture["ok"] is True
    assert fixture["bytes_written"] == len("XY".encode("utf-8")) == 2
    assert fixture["bytes_written"] < len("AAAA BBBB CCCC".encode("utf-8"))


def test_edit_file_replace_all_bytes_written_scales_with_occurrences():
    """'XX YY XX YY XX' has three 'XX' occurrences replaced with 'Q' --
    bytes_written = 3 * len('Q'), not the length of one replacement."""
    fixture = _B["edit_file_bytes_written_replace_all"]
    assert fixture["ok"] is True
    assert fixture["bytes_written"] == 3 * len("Q".encode("utf-8")) == 3
    assert fixture["result"] == "edited r.txt: replaced 3 occurrences"


def test_edit_file_old_string_not_found_is_a_recoverable_tool_error():
    fixture = _B["edit_file_old_string_not_found"]
    assert fixture["ok"] is False
    assert "not found" in fixture["error"]


def test_edit_file_ambiguous_match_without_replace_all_is_refused():
    fixture = _B["edit_file_ambiguous_without_replace_all"]
    assert fixture["ok"] is False
    assert "not unique" in fixture["error"]


# --- list_dir shape -------------------------------------------------------


def test_list_dir_entries_are_sorted_with_trailing_slash_on_directories():
    fixture = _B["list_dir_shape"]
    assert fixture["ok"] is True
    assert fixture["result"] == "a.txt\nb.txt\nsub/"


def test_list_dir_on_a_file_is_a_recoverable_tool_error():
    fixture = _B["list_dir_not_a_directory"]
    assert fixture["ok"] is False
    assert "not a directory" in fixture["error"]


# --- run_command: truncation boundary + result shape -----------------------


def test_run_command_truncation_boundary_is_exact():
    """The formatted result is f"exit={code}\\n{stdout}{stderr}" -- the
    7-char "exit=0\\n" prefix counts toward the cap, so the boundary sits at
    max_output_chars - 7 bytes of raw command output, not at max_output_chars
    itself."""
    not_truncated = _B["run_command_truncation_boundary_not_truncated"]
    truncated = _B["run_command_truncation_boundary_truncated"]

    assert not_truncated["ok"] is True
    assert len(not_truncated["result"]) == _CONSTANTS["max_output_chars"]
    assert "truncated at" not in not_truncated["result"]

    assert truncated["ok"] is True
    assert "truncated at 25000 chars" in truncated["result"]
    assert len(truncated["result"]) == _CONSTANTS["max_output_chars"] + len(
        "\n... [truncated at 25000 chars]"
    )


def test_run_command_result_is_exit_then_stdout_then_stderr_unlabelled():
    """stdout and stderr are concatenated into one string with no label --
    colleague/tools.py:1048's `body = (proc.stdout or "") + (proc.stderr or "")`."""
    fixture = _B["run_command_exit_code_and_body_shape"]
    assert fixture["ok"] is True
    assert fixture["result"] == "exit=3\nout-line\nerr-line\n"


def test_run_command_missing_required_command_is_a_recoverable_tool_error():
    fixture = _B["run_command_missing_required_command"]
    assert fixture["ok"] is False
    assert "command" in fixture["error"]


# --- view_media: images-only, size-capped ----------------------------------


def test_view_media_ok_produces_an_image_url_content_part():
    fixture = _B["view_media_ok"]
    assert fixture["ok"] is True
    assert fixture["media_part"]["type"] == "image_url"
    assert fixture["media_part"]["image_url"]["url"].startswith("data:image/png;base64,")


def test_view_media_is_images_only_audio_is_refused():
    fixture = _B["view_media_audio_rejected"]
    assert fixture["ok"] is False
    assert "images only" in fixture["error"]


def test_view_media_oversize_is_refused_at_the_4mib_cap():
    fixture = _B["view_media_oversize_rejected"]
    assert fixture["ok"] is False
    assert str(_CONSTANTS["max_media_bytes"]) in fixture["error"]


def test_view_media_unknown_extension_is_refused():
    fixture = _B["view_media_unknown_extension_rejected"]
    assert fixture["ok"] is False
    assert "Unknown attachment extension" in fixture["error"]


# --- ToolExecutor.execute: the exception-wrap (colleague/tools.py:788-800) -


def test_execute_wraps_a_non_tool_error_into_a_recoverable_tool_error():
    """A handler crash on malformed model input must become a model-visible
    ToolError, never escape and abort the whole drive."""
    fixture = _B["execute_wraps_non_tool_error"]
    assert fixture["ok"] is False
    assert fixture["error_type"] == "ToolError"
    assert "read_file failed:" in fixture["error"]
    assert "ValueError" in fixture["error"]
    assert "check the tool's argument schema and retry" in fixture["error"]


def test_the_raw_handler_exception_is_not_wrapped_without_execute():
    """Without execute()'s wrap, the identical crash escapes as a raw,
    un-recoverable exception -- proof the wrap does real work, not just
    relabels something that was already safe."""
    fixture = _B["execute_wraps_non_tool_error"]
    raw = fixture["raw_handler_exception"]
    assert raw["ok"] is False
    assert raw["error_type"] == "ValueError"
    assert raw["error_type"] != fixture["error_type"]


def test_execute_unknown_tool_raises_a_distinct_error_type():
    """UnknownToolError is distinguished from ToolError so a broken
    tool-call protocol (a name that can never exist) can be told apart from
    an ordinary bad call to a real tool."""
    fixture = _B["execute_unknown_tool"]
    assert fixture["ok"] is False
    assert fixture["error_type"] == "UnknownToolError"
    assert fixture["error_type"] != "ToolError"
