#!/usr/bin/env python3
"""Render the workforce handoff bundle from authoritative devague state.

`.devague/plans/<slug>.json` is the source of truth. This script writes a
**generated projection** of it into devague's own export lane, so the handoff
uses devague's normal layout and no invented directory:

    .devague/plans/<slug>.json          # authoritative state (committed)
    docs/specs/<created>-<slug>.md      # devague plan export lane
    docs/plans/<created>-<slug>.md      # THIS projection, same path devague
                                        # plan export will write when #85 lands

`plan.md` must never be hand-edited — it carries a SHA-256 of the plan JSON it
was rendered from, and `--check` fails when the two disagree. Regenerate it
whenever the devague state changes.

This exists because devague cannot currently export a milestone-scoped plan:
its coverage gate requires every confirmed target in the parent frame to be
covered by a task, so a plan that deliberately defers targets to later
milestones never converges. See
https://github.com/agentculture/devague/issues/85. When that lands, this
script should be deleted in favour of `devague plan export`.

Usage::

    python3 scripts/render_plan.py --slug guarded-local-operations-plane
    python3 scripts/render_plan.py --slug <slug> --check   # CI drift gate
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DEVAGUE_ISSUE = "https://github.com/agentculture/devague/issues/85"
GENERATED_MARKER = "<!-- GENERATED by scripts/render_plan.py — do not edit -->"


def sha256_of(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def waves_from(tasks: list[dict]) -> list[list[str]]:
    """Kahn layering over confirmed tasks; mirrors `devague plan waves`."""
    active = {t["id"]: t for t in tasks if t.get("status") == "confirmed"}
    remaining = dict(active)
    placed: set[str] = set()
    waves: list[list[str]] = []
    while remaining:
        layer = sorted(
            tid
            for tid, t in remaining.items()
            if all(d in placed or d not in active for d in (t.get("deps") or []))
        )
        if not layer:  # cycle — report rather than loop forever
            waves.append(sorted(remaining))
            break
        waves.append(layer)
        placed.update(layer)
        for tid in layer:
            remaining.pop(tid)
    return waves


def render(plan: dict, plan_path: Path, stamp: str) -> str:
    tasks = plan.get("tasks", [])
    confirmed = [t for t in tasks if t.get("status") == "confirmed"]
    targets = {t["id"] for t in plan.get("targets", [])}
    covered = {c for t in confirmed for c in (t.get("covers") or [])}
    deferred = sorted(targets - covered)
    risks = plan.get("risks", [])
    by_id = {t["id"]: t for t in confirmed}

    out: list[str] = []
    a = out.append

    a(GENERATED_MARKER)
    a(f"# Plan projection — {plan.get('slug', '?')}")
    a("")
    a("> **This file is a generated projection, not an authored plan.**")
    a(
        "> The authoritative state is `.devague/plans/"
        + str(plan.get("slug", "?"))
        + ".json`. Do not edit"
    )
    a("> this file; regenerate it with `scripts/render_plan.py` whenever the JSON")
    a("> changes. Any divergence between the two means this file is stale.")
    a("")
    a(f"- **Plan slug**: `{plan.get('slug', '?')}`")
    a(f"- **Source frame**: `{plan.get('frame_slug', '?')}`")
    a(f"- **Generated**: {stamp}")
    a(f"- **Source**: `{plan_path.relative_to(REPO).as_posix()}`")
    a(f"- **SHA-256 of source**: `{sha256_of(plan_path)}`")
    a(f"- **Confirmed tasks**: {len(confirmed)}")
    a(f"- **Coverage**: {len(covered & targets)} / {len(targets)} targets")
    a("")
    a("## Why this file exists")
    a("")
    a("`devague plan export` cannot render this plan. Its coverage gate requires")
    a("every confirmed target in the parent frame to be covered by a task, but this")
    a("plan is deliberately milestone-scoped and defers the targets listed below to")
    a("separately scoped plans. Adding placeholder tasks to satisfy the gate would")
    a("mean claiming delivery of work this plan does not do, so the plan is exported")
    a("through this projection instead.")
    a("")
    a(f"Tracked upstream as <{DEVAGUE_ISSUE}>. When deferred-target semantics land,")
    a("delete this script and use `devague plan export`.")
    a("")

    a("## Execution waves")
    a("")
    a("Dependency layering over confirmed tasks. Same-wave tasks have no")
    a("inter-task dependencies; file disjointness is asserted per task under")
    a("`owns:` and must be re-checked before fan-out.")
    a("")
    a("```text")
    for i, wave in enumerate(waves_from(tasks)):
        a(f"wave {i}: {', '.join(wave)}")
    a("```")
    a("")

    a("## Tasks")
    a("")
    for tid in sorted(by_id, key=lambda x: int(x[1:])):
        t = by_id[tid]
        a(f"### `{tid}`")
        a("")
        a(t.get("summary", ""))
        a("")
        deps = t.get("deps") or []
        a(f"- **Depends on**: {', '.join(f'`{d}`' for d in deps) if deps else '_none_'}")
        covers = t.get("covers") or []
        a(f"- **Covers**: {', '.join(f'`{c}`' for c in covers) if covers else '_none_'}")
        crit = t.get("acceptance_criteria") or []
        a(f"- **Acceptance criteria** ({len(crit)}):")
        for c in crit:
            a(f"  - {c}")
        a("")

    a("## Deferred targets")
    a("")
    a("These are **confirmed roadmap requirements**, deliberately not covered by")
    a("this plan and deferred to separately scoped plans. No task in this plan")
    a("claims to deliver them.")
    a("")
    if deferred:
        for tid in deferred:
            a(f"- `{tid}`")
    else:
        a("_none_")
    a("")

    open_risks = [r for r in risks if not r.get("resolved")]
    closed_risks = [r for r in risks if r.get("resolved")]

    a("## Open risks")
    a("")
    if open_risks:
        for r in open_risks:
            a(f"- **`{r.get('id')}`** ({r.get('kind')}): {r.get('text')}")
    else:
        a("_none_")
    a("")

    if closed_risks:
        a("## Resolved risks")
        a("")
        a("Retained for the audit trail. These are NOT live — do not action them.")
        a("")
        for r in closed_risks:
            a(f"- **`{r.get('id')}`** ({r.get('kind')}) — {r.get('resolution', 'resolved')}")
        a("")

    a("---")
    a("")
    a(f"{GENERATED_MARKER}")
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Render the workforce handoff bundle.")
    ap.add_argument("--slug", required=True)
    ap.add_argument("--check", action="store_true", help="fail if plan.md is stale")
    args = ap.parse_args(argv)

    plan_path = REPO / ".devague" / "plans" / f"{args.slug}.json"
    if not plan_path.is_file():
        print(f"error: no devague plan state at {plan_path}", file=sys.stderr)
        print("hint: run 'devague plan show' to list plans", file=sys.stderr)
        return 2

    plan = json.loads(plan_path.read_text(encoding="utf-8"))
    created = str(plan.get("created", ""))[:10] or "undated"
    out_dir = REPO / "docs" / "plans"
    md_path = out_dir / f"{created}-{args.slug}.md"

    if args.check:
        if not md_path.is_file():
            print(f"error: {md_path} missing — run render_plan.py", file=sys.stderr)
            return 1
        digest = sha256_of(plan_path)
        if digest not in md_path.read_text(encoding="utf-8"):
            print("error: plan.md is stale — devague state changed", file=sys.stderr)
            print(f"hint: regenerate with render_plan.py --slug {args.slug}", file=sys.stderr)
            return 1
        print(f"plan.md is current ({digest[:12]})")
        return 0

    out_dir.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")

    md_path.write_text(render(plan, plan_path, stamp), encoding="utf-8")
    print(f"wrote {md_path.relative_to(REPO)}")
    print(f"  projection of .devague/plans/{args.slug}.json")
    print(f"  sha256 {sha256_of(plan_path)[:12]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
